[workspace]
authors = ["Brenda Soljic <brendasoljic8@gmail.com>"]
channels = ["conda-forge"]
name = "BINF-5507-Materials"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.3,<3.15"
ipykernel = ">=7.1.0,<8"
numpy = ">=2.4.2,<3"
pandas = ">=3.0.0,<4"
matplotlib = ">=3.10.8,<4"
seaborn = ">=0.13.2,<0.14"
scikit-learn = ">=1.8.0,<2"
tqdm = ">=4.67.3,<5"
